---
- name: add the repository
  yum_repository:
    name: consul
    description: add consul repository
    baseurl: https://rpm.releases.hashicorp.com/RHEL/$releasever/$basearch/stable
    gpgkey: https://rpm.releases.hashicorp.com/gpg

- name: install consul
  yum:
    name: consul
    state: present

- name: consul config file
  template:
    src: consul.sh.j2
    dest: /etc/consul.d/consul.hcl
  notify: start consul
