---
- name: add the repository
  yum_repository:
    name: consul
    description: add consul repository
    baseurl: https://rpm.releases.hashicorp.com/RHEL/$releasever/$basearch/stable
    gpgkey: https://rpm.releases.hashicorp.com/gpg

- name: install consul
  yum:
    name: consul
    state: present
  notify: Uncomment server
