---

- name: fabio job
  template:
    src: fabio.nomad
    dest: /opt/fabio.nomad
  notify: Start fabio

- name: Alertmanager job
  template:
    src: alertmanager.nomad
    dest: /opt/alertmanager.nomad
  notify: Start alertmanager

- name: webserver job
  template:
    src: webserver.nomad
    dest: /opt/webserver.nomad
  notify: Start webserver

#- name: prometheus job
#  template:
#    src: prometheus.nomad
#    dest: /opt/prometheus.nomad
#  notify: Start prometheus

- name: Grafana template
  template: 
    src: jobs.hcl.sh.j2
    dest: /opt/nomad/grafana.hcl
  vars:
    job_name: grafana
    job_image: grafana/grafana:latest
    job_port: 3000
  notify: Start grafana
