---
- name: Download node_exporter
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz
    dest: /home/vagrant
    mode: '0776'
    

- name: Extract node_exporter
  unarchive:
    src: /home/vagrant/node_exporter-1.0.1.linux-amd64.tar.gz
    dest: /home/vagrant

- name: Move node_exporter
  command: mv /home/vagrant/node_exporter-1.0.1.linux-amd64/node_exporter /usr/local/bin/

- name: Node_exporter .service file
  template: 
    src: node_exporter.service.sh.j2
    dest: /etc/systemd/system/node_exporter.service

- name: Start node_exporter
  service:
    name: node_exporter
    state: started