---
- name: Uncomment server
  lineinfile:
    path: /etc/consul.d/consul.hcl
    regexp: '#server = true'
    line: server = {{server_enable_disable}}
  notify: Uncomment bootstrap

- name: Uncomment bootstrap
  lineinfile:
    path: /etc/consul.d/consul.hcl
    regexp: '#bootstrap_expect=3'
    line: bootstrap_expect={{amount_bootstrap}}
  notify: Uncomment retry

- name: Uncomment retry
  lineinfile:
    path: /etc/consul.d/consul.hcl
    regexp: '#retry_join = ["10.0.4.67"]'
    line: retry_join = ["{{ server_ip }}"]
  notify: Add bind

- name: Add bind
  lineinfile:
    path: /etc/consul.d/consul.hcl
    line: bind_addr = "{{bind_addr}}"
    insertafter: 'retry_join'
    create: yes
  notify: Add node_name

- name: Add node_name
  lineinfile:
    path: /etc/consul.d/consul.hcl
    line: node_name = "{{node_name}}"
    insertafter: 'bind_addr'
    create: yes
  notify: started consl

- name: started consul
  service:
    name: consul
    state: started








