---
- name: add docker-ce repository
  yum_repository:
    name: docker-ce
    description: add docker-ce repository
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
    gpgkey: https://download.docker.com/linux/centos/gpg

- name: install docker-ce
  yum:
    name: docker-ce
    state: present
  notify: started docker-ce