# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
#  config.vbguest.auto_update = false
  config.vm.box = "centos/7"

  config.vm.define :server do |server|
    server.vm.hostname = "server"
    server.vm.network "private_network", ip: "192.168.2.4", virtualbox_internet:  "mynetwork"

    server.vm.provision "ansible_local" do |ansible|
      ansible.config_file = "ansible/ansible.cfg"
      ansible.playbook = "ansible/plays/server.yml"
      ansible.groups = {
        "servers" => ["server"],
#        "clients" => ["node1", "node2"]
#       "servers:vars" => {"crond__content" => "servers_value"}
      }
      ansible.host_vars = {
#        "server" => {"crond__content" => "server_value"}
      }
#      ansible.verbose = '-vvv'
    end
  end

  #config.vm.define "node1" do |node1|
   #node1.vm.hostname = "node1"
   #node1.vm.network "private_network", ip: "192.168.2.5", virtualbox__internet: "mynetwork"
   #end

  #config.vm.define "node2" do |node2|
   #node2.vm.hostname = "node2"
   #node2.vm.network "private_network", ip: "192.168.2.6", virtualbox__internet: "mynetwork"
   #end

end
